#!/bin/bash

if [ -L "$0" ]; then
    LK=$(readlink "$0")
    if [[ $LK == /* ]]; then
        SCRIPT_PATH=$LK
    else
        SCRIPT_PATH="$(dirname "$0")/$LK"
    fi
else
    SCRIPT_PATH=$0
fi

node "$(dirname "$SCRIPT_PATH")/tv_grab_skylife.js" $*
#node "$(dirname "$SCRIPT_PATH")/tv_grab_daum.js" $*
#node "$(dirname "$SCRIPT_PATH")/tv_grab_naver.js" $*
#node "$(dirname "$SCRIPT_PATH")/tv_grab_tvg.js" $*
